# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cell_offset_sax_vc <- function(qnorm, x, y, qoff, xoff, yoff) {
    .Call('_idxrepr_cell_offset_sax_vc', PACKAGE = 'idxrepr', qnorm, x, y, qoff, xoff, yoff)
}

cell_offset_vc <- function(qnorm, x, y, xoff, yoff) {
    .Call('_idxrepr_cell_offset_vc', PACKAGE = 'idxrepr', qnorm, x, y, xoff, yoff)
}

d_ed <- function(x, y, TT) {
    .Call('_idxrepr_d_ed', PACKAGE = 'idxrepr', x, y, TT)
}

d_sax <- function(m, x, y) {
    .Call('_idxrepr_d_sax', PACKAGE = 'idxrepr', m, x, y)
}

d_seassaxpaa <- function(x, y, B, L, f, qseas) {
    .Call('_idxrepr_d_seassaxpaa', PACKAGE = 'idxrepr', x, y, B, L, f, qseas)
}

d_seassaxres <- function(x, y, B, L, f, qres, qseas) {
    .Call('_idxrepr_d_seassaxres', PACKAGE = 'idxrepr', x, y, B, L, f, qres, qseas)
}

d_seassaxres_lut <- function(x, y, T, B, L, mres, mseas) {
    .Call('_idxrepr_d_seassaxres_lut', PACKAGE = 'idxrepr', x, y, T, B, L, mres, mseas)
}

d_ed_tic <- function(x, y, TT) {
    .Call('_idxrepr_d_ed_tic', PACKAGE = 'idxrepr', x, y, TT)
}

d_sax_tic <- function(n, w, m, x, y) {
    .Call('_idxrepr_d_sax_tic', PACKAGE = 'idxrepr', n, w, m, x, y)
}

#' @export
tic <- function() {
    .Call('_idxrepr_tic', PACKAGE = 'idxrepr')
}

to_series_dseas <- function(sigma12, l1, l2, n) {
    .Call('_idxrepr_to_series_dseas', PACKAGE = 'idxrepr', sigma12, l1, l2, n)
}

#' @export
toc <- function(start) {
    .Call('_idxrepr_toc', PACKAGE = 'idxrepr', start)
}

write_float8_c <- function(x, fp, size, mod) {
    invisible(.Call('_idxrepr_write_float8_c', PACKAGE = 'idxrepr', x, fp, size, mod))
}

write_uint2_c <- function(x, fp, size, mod) {
    invisible(.Call('_idxrepr_write_uint2_c', PACKAGE = 'idxrepr', x, fp, size, mod))
}

write_uint1_c <- function(x, fp, size, mod) {
    invisible(.Call('_idxrepr_write_uint1_c', PACKAGE = 'idxrepr', x, fp, size, mod))
}

read_float8_c <- function(fp, size, pos1, pos2) {
    .Call('_idxrepr_read_float8_c', PACKAGE = 'idxrepr', fp, size, pos1, pos2)
}

read_uint2_c <- function(fp, size, pos1, pos2) {
    .Call('_idxrepr_read_uint2_c', PACKAGE = 'idxrepr', fp, size, pos1, pos2)
}

read_uint1_c <- function(fp, size, pos1, pos2) {
    .Call('_idxrepr_read_uint1_c', PACKAGE = 'idxrepr', fp, size, pos1, pos2)
}

